\echo Use "CREATE EXTENSION xxhash" to load this file. \quit

-- xxhash
CREATE OR REPLACE FUNCTION xxh32(text) RETURNS varchar(8) AS 'MODULE_PATHNAME', 'pg_xxh32' LANGUAGE C IMMUTABLE STRICT;
CREATE OR REPLACE FUNCTION xxh64(text) RETURNS varchar(16) AS 'MODULE_PATHNAME', 'pg_xxh64' LANGUAGE C IMMUTABLE STRICT;

-- xxhash3
CREATE OR REPLACE FUNCTION xxh3_64(text) RETURNS varchar(16) AS 'MODULE_PATHNAME', 'pg_xxh3_64' LANGUAGE C IMMUTABLE STRICT;
CREATE OR REPLACE FUNCTION xxh3_128(text) RETURNS varchar(32) AS 'MODULE_PATHNAME', 'pg_xxh3_128' LANGUAGE C IMMUTABLE STRICT;
CREATE OR REPLACE FUNCTION xxh128(text) RETURNS varchar(32) AS 'MODULE_PATHNAME', 'pg_xxh3_128' LANGUAGE C IMMUTABLE STRICT;  -- alias
